name: test-workflow
on: push
jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: actions/checkout@v3
        - name: install node.js
          uses: actions/setup-node@v1
          with: 
              node-version: 20
        - name: test application
          run: npm test
      
